---
- hosts: nodes
  become: yes
  become_user: root
  tasks:
    - name: install yum utils
      yum:
        name: yum-utils
        state: latest
    - name: Install pre-req
      yum:
        name:
          - wget
          - git
          - net-tools
          - bind-utils
          - iptables-services
          - bridge-utils
          - bash-completion
          - kexec-tools 
          - sos
          - psacct
          - bash-completion
          - kexec-tools
        state: present
    - name: Update Centos kernel
      yum:
        name: "*"
        state: latest
    
    - name: Install Docker
      yum:
        name:
           - docker
        state: present
      
    - name: Make sure a docker is running
      systemd:
        state: started
        name: docker
        
    - name: restart system to reboot to newest kernel
      shell: "sleep 5 && reboot"
      async: 1
      poll: 0
    
    - name: wait for 10 seconds
      pause:
        seconds: 10

    # - name: Rebooting
    #   command: shutdown -r now "Reboot required for updated kernel"
    #   async: 0
    #   poll: 0
    #   ignore_errors: true
    #   when: reboot_hint.stdout.find("reboot") != -1
    #   register: rebooting